<Type Name="ThreadStartException" FullName="System.Threading.ThreadStartException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="c01026a3527c9880f411b7bfa6b44823d15374e2" />
    <Meta Name="ms.sourcegitcommit" Value="6a0b904069161bbaec4ffd02aa7d9cf38c61e72e" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="de-DE" />
    <Meta Name="ms.lasthandoff" Value="06/24/2018" />
    <Meta Name="ms.locfileid" Value="36605554" />
  </Metadata>
  <TypeSignature Language="C#" Value="public sealed class ThreadStartException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit ThreadStartException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.Threading.ThreadStartException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class ThreadStartException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class ThreadStartException sealed : SystemException" />
  <TypeSignature Language="F#" Value="type ThreadStartException = class&#xA;    inherit SystemException" />
  <AssemblyInfo>
    <AssemblyName>System.Threading.Thread</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <AssemblyVersion>4.1.1.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netframework-4.5">System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="740fb-101">Die Ausnahme, die ausgelöst wird, wenn ein Fehler in einem verwalteten Thread auftritt, nachdem der Thread des zugrunde liegenden Betriebssystems gestartet wurde, jedoch bevor der Thread bereit ist, Benutzercode auszuführen.</span>
      <span class="sxs-lookup">
        <span data-stu-id="740fb-101">The exception that is thrown when a failure occurs in a managed thread after the underlying operating system thread has been started, but before the thread is ready to execute user code.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="740fb-102">Die zurückgegebene Ausnahme die <xref:System.Exception.InnerException%2A> Eigenschaft enthält Informationen über die Ursache des Fehlers.</span><span class="sxs-lookup"><span data-stu-id="740fb-102">The exception returned by the <xref:System.Exception.InnerException%2A> property provides information about the reason for the failure.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members />
</Type>